config/routes.rb
Rails.application.routes.draw do

  root   'categories#index'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get     '/signup', to: 'users#new'
  post    '/signup', to: 'users#create'
  get     '/users',  to: 'users#index'
  get     '/user',   to: 'users#show'
  resources :users

  resources :goods, only: [:index, :show]
  get     '/search/goods', to: 'goods#search'

  resources :categories do
    resources :goods
  end

  get       '/shopping_cart',                to:  'shopping_cart#show'
  get       '/shopping_cart/total_sum',      to:  'shopping_cart#total_sum'
  post      '/shopping_cart/goods/:good_id', to:  'shopping_cart#add'
  delete    '/shopping_cart/goods/:good_id', to:  'shopping_cart#remove'

  resources :orders do
    resources :goods
    resources :credits
  end

  get       '/credits',                        to: 'credits#index'
  post      '/credits/:id',                    to: 'credits#create'

  resources :banks

  get       '/payments',    to: 'payments#index'
  post      '/payment',     to: 'payments#new'

  get       '/admin/dashboard',   to: 'admin#index'
  namespace :admin do
    resources :users, only: [:index, :change_role]
    post      '/users/:user_id/role',to: 'users#change_role'

    get       '/orders',            to: 'orders#index'
    post      '/orders/:order_id',  to: 'orders#confirm'
    delete    '/orders/:order_id',  to: 'orders#cancel'

    resources :categories, only: [:index, :create]
    put       '/categories/:category_id',     to: 'categories#update'
    delete    '/categories/:category_id',     to: 'categories#delete'

    resources :goods, only: [:index, :create]
    put       '/goods/:good_id',     to: 'goods#update'
    delete    '/goods/:good_id',     to: 'goods#delete'
    get       '/search/goods',       to: 'goods#search'

    resources :credits, only: [:create]

    resources :orders, only: [:index]
    post      '/orders/:order_id/credit',     to: 'credits#create'
    delete    '/orders/:order_id',            to: 'orders#cancel'


  end

end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  has_and_belongs_to_many :goods
  belongs_to :user

  validates :user_id, presence: true

  before_destroy {goods.clear}

  def total_sum
    sum = 0
    self.goods.each do |good|
      sum += good.price
    end
    sum
  end
end

app/controllers/shopping_cart_controller.rb
class ShoppingCartController < ApplicationController
  load_and_authorize_resource

  def show
    @shopping_cart = current_user.shopping_cart
  end

  #add good to shopping cart of current user
  def add
    good = Good.find(params[:good_id])
    unless current_user.shopping_cart.goods.exists?(good)
      current_user.shopping_cart.goods << good
    end
    redirect_to shopping_cart_path
  end

  def remove
    good = Good.find(params[:good_id])
    current_user.shopping_cart.goods.delete(good)
    redirect_to shopping_cart_path
  end

  def total_sum
    l = current_user.shopping_cart.total_sum
    n = params[:months].to_i
    i = current_bank.interest_rate / (12 * 100)
    credit_total_sum = Credit.credit_total(l, n, i)

    respond_to do |format|
      format.json { render json: {'credit_total_sum': credit_total_sum.round(2) }}
    end
  end

end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper

  def shopping_cart
    if current_user
      @shopping_cart = current_user.shopping_cart
    else
      ShoppingCart.new
    end
  end

  def goods_in_cart
    @current_user.shopping_cart.goods.count
  end
end

app/views/shopping_cart/show.html.erb
<div class="content">
  <h2>Cart <span class="label label-default"></span></h2>

    <%= form_tag orders_path, method: :post do %>

      <%= render 'layouts/flash_messages' %>

      <table class="table table-hover">

        <thead>
        <tr>
          <th>Product</th>
          <!--<th>Quantity</th>-->
          <th class="text-center">Price</th>
          <!--<th class="text-center">Total</th>-->
          <th>&nbsp;</th>
        </tr>
        </thead>


        <tbody>
          <% @shopping_cart.goods.each do |good| %>
              <tr>
                <td class="col-sm-8 col-md-6">
                  <div class="media">
                    <a class="thumbnail pull-left" href="#">
                      <!--image of good-->
                      <%= image_tag good.photo, class: 'media-object' %>
                      <!--<img class="media-object" src="images/gibson_les_paul_standard_2012_hs.png">-->
                    </a>
                    <div class="media-body">
                      <h4 class="media-heading">
                        <%= link_to "#{good.name}", good_path(good.id) %>
                        <!--<a href="item.html">Gibson Les Paul Standard 2012 HS</a>-->
                      </h4>
                      <span>Status: </span>
                      <span class="text-success">
                      <strong>In Stock</strong>
                    </span>
                    </div>
                  </div>
                </td>
                <!--<td class="col-sm-1 col-md-1" style="text-align: center">-->
                  <!--  -->
                  <!--<input type="number" class="form-control" id="qty_input" value="1">-->
                <!--</td>-->
                <td class="col-sm-1 col-md-1 text-center">
                  <strong class="good_price"><%= good.price %></strong>
                </td>
                <!--<td class="col-sm-1 col-md-1 text-center">-->
                  <!--<strong>sum</strong>-->
                <!--</td>-->
                <td class="col-sm-1 col-md-1 text-center">
                  <%= link_to "/shopping_cart/goods/#{good.id}",
                              method: :delete,
                              class: 'btn btn-danger' do %>
                      <span class="glyphicon glyphicon-remove"></span> Remove
                  <% end %>

                  <!--<button type="button" class="btn btn-danger">-->
                  <!--<span class="glyphicon glyphicon-remove"></span> Remove-->
                  <!--</button></td>-->
                  </tr>
          <% end %>
        </tbody>


        <tfoot>
        <tr>
          <td> &nbsp;
            <div class="slide">
              <div class="col-md-2">
                <label for="months">Months:</label>
              </div>
              <div class="col-md-8">
                <!--<input type="range" min="2" max="84" id="sliderInput"-->
                       <!--oninput="monthsAmountSlider()" value="2">-->

                <input type="text" id="sliderInput" data-slider-id="sliderInputDS"
                       data-slider-min="2" data-slider-max="84" data-slider-step="1"
                        data-slider-value="2" data-slider-orientation="horisontal"
                />
              </div>
              <div class="col-md-2">
                <%= text_field_tag :months, 2, id: 'numberInput', class: 'form-control' %>
                <!--<input type="number" id="numberInput" class="form-control" value="2">-->
              </div>
            </div>
          </td>
          <!--<td> &nbsp; </td>-->
          <!--<td> &nbsp; </td>-->
          <td>
            <div class="slide"></div>
          </td>
          <td>
            &nbsp;
          </td>
        </tr>
        <tr>
          <td class="text-center"><h4>Monthly: <span id="monthly">0</span> UAH</h4></td>
          <td class="text-center"><h3>Total</h3></td>
          <td class="text-center"><h3><span id="total_sum">0</span> UAH</h3></td>
        </tr>
        <tr>
          <td> &nbsp; </td>
          <!--<td> &nbsp; </td>-->
          <!--<td> &nbsp; </td>-->
          <td>

            <%= link_to :back, class: 'btn btn-default' do %>
              <span class="glyphicon glyphicon-shopping-cart"></span> Back
            <% end %>
          </td>
          <td class="text-center">
            <%= submit_tag 'Checkout',  class: 'btn btn-success' %>
          </td>
        </tr>
        </tfoot>
      </table>
    <% end %>
</div>