config/routes.rb
Rails.application.routes.draw do

  root   'categories#index'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get     '/signup', to: 'users#new'
  post    '/signup', to: 'users#create'
  get     '/users',  to: 'users#index'
  get     '/user',   to: 'users#show'
  resources :users

  resources :goods, only: [:index, :show]
  get     '/search/goods', to: 'goods#search'

  resources :categories do
    resources :goods
  end

  get       '/shopping_cart',                to:  'shopping_cart#show'
  get       '/shopping_cart/total_sum',      to:  'shopping_cart#total_sum'
  post      '/shopping_cart/goods/:good_id', to:  'shopping_cart#add'
  delete    '/shopping_cart/goods/:good_id', to:  'shopping_cart#remove'

  resources :orders do
    resources :goods
    resources :credits
  end

  get       '/credits',                        to: 'credits#index'
  post      '/credits/:id',                    to: 'credits#create'

  resources :banks

  get       '/payments',    to: 'payments#index'
  post      '/payment',     to: 'payments#new'

  get       '/admin/dashboard',   to: 'admin#index'
  namespace :admin do
    resources :users, only: [:index, :change_role]
    post      '/users/:user_id/role',to: 'users#change_role'

    get       '/orders',            to: 'orders#index'
    post      '/orders/:order_id',  to: 'orders#confirm'
    delete    '/orders/:order_id',  to: 'orders#cancel'

    resources :categories, only: [:index, :create]
    put       '/categories/:category_id',     to: 'categories#update'
    delete    '/categories/:category_id',     to: 'categories#delete'

    resources :goods, only: [:index, :create]
    put       '/goods/:good_id',     to: 'goods#update'
    delete    '/goods/:good_id',     to: 'goods#delete'
    get       '/search/goods',       to: 'goods#search'

    resources :credits, only: [:create]

    resources :orders, only: [:index]
    post      '/orders/:order_id/credit',     to: 'credits#create'
    delete    '/orders/:order_id',            to: 'orders#cancel'


  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :credit
  #has_one :credit

  validates :amount, presence: true
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  load_and_authorize_resource

  def index
    @payment = Payment.new
    @orders = current_user.orders.where(status: :confirmed)
  end

  def new
    @payment = Payment.new(payment_params)
    @credit = Credit.find(@payment.credit_id)
    if @credit.order.is?('confirmed')
      if @payment.amount.to_f >= @credit.minimal_payment.to_f
        @credit.add_payment(@payment)
        flash[:success] = "Payment for credit #{@credit.id} successfully made!"
      else
        flash[:error] = 'Amount is less than minimal payment for this credit!'
      end
    else
      flash[:error] = "Payment not available for that credit! Credit status #{@credit.order.status}"
    end

    redirect_to payments_path
  end

  private
    def payment_params
      params.require(:payment).permit(:credit_id, :amount)
    end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/index.html.erb
<div class="row">
  <div class="col-md-2">
    <%= render 'layouts/navigation' %>
  </div>

  <div class="col-md-10">
    <%= render 'layouts/flash_messages' %>
    <%= form_for @payment, url: payment_path do |f| %>
        <table class="table table-hover">
          <thead>
          <tr>
            <th class="col-sm-4 col-md-4 text-center">Credit No</th>
            <th class="col-sm-2 col-md-2 text-center">Total</th>
            <th class="col-sm-2 col-md-2 text-center">Minimal payment</th>
            <th class="col-sm-2 col-md-2 text-center">Rest</th>
            <th class="col-sm-2 col-md-2 text-center">Fine</th>
          </tr>
          </thead>
          <tbody>
          <% @orders.each do |order| %>
              <tr>
                <td class="col-sm-2 col-md-2 text-center">
                  <%= f.radio_button :credit_id, order.credit.id %>
                  <div class="dropdown">
                    <label class="btn btn-default dropdown-toggle"
                           type="button" id="dropdownMenu1"
                           data-toggle="dropdown"
                           aria-haspopup="true"
                           aria-expanded="true">
                      <%= order.credit.id %><span class="caret"></span>
                    </label>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                      <% order.goods.each do |good| %>
                          <li>
                            <div class="media">
                              <a class="thumbnail pull-left" href="#">
                                <%= image_tag good.photo %>
                              </a>
                              <div class="media-body">
                                <p class="media-heading">
                                  <%= link_to good.name, good %>
                                  Cost: <%= good.price %> UAH<br>
                                </p>
                              </div>
                            </div>
                          </li>
                      <% end %>
                    </ul>
                  </div>
                </td>
                <td class="col-sm-2 col-md-2 text-center"><strong><%= order.total_price %> UAH</strong></td>
                <td class="col-sm-1 col-md-1 text-center"><strong><%= order.credit.minimal_payment %> UAH</strong></td>
                <td class="col-sm-2 col-md-2 text-center"><strong><%= order.credit.rest %> UAH</strong></td>
                <td class="col-sm-2 col-md-2 text-center"><strong><%= order.credit.fine %></strong></td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <div class="input-field">
          <div class="form-group">
            <div class="input-group">
          <span class="input-group-addon" id="basic-addon1">
            <span class="glyphicon glyphicon-usd" aria-hidden="true"></span>
          </span>
              <%= f.number_field :amount, class: 'form-control bfh-phone'%>
              <span class="input-group-btn">
            <%= f.submit 'Pay', class: 'btn btn-success' %>
          </span>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>
