config/routes.rb
Rails.application.routes.draw do

  root   'categories#index'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get     '/signup', to: 'users#new'
  post    '/signup', to: 'users#create'
  get     '/users',  to: 'users#index'
  get     '/user',   to: 'users#show'
  resources :users

  resources :goods, only: [:index, :show]
  get     '/search/goods', to: 'goods#search'

  resources :categories do
    resources :goods
  end

  get       '/shopping_cart',                to:  'shopping_cart#show'
  get       '/shopping_cart/total_sum',      to:  'shopping_cart#total_sum'
  post      '/shopping_cart/goods/:good_id', to:  'shopping_cart#add'
  delete    '/shopping_cart/goods/:good_id', to:  'shopping_cart#remove'

  resources :orders do
    resources :goods
    resources :credits
  end

  get       '/credits',                        to: 'credits#index'
  post      '/credits/:id',                    to: 'credits#create'

  resources :banks

  get       '/payments',    to: 'payments#index'
  post      '/payment',     to: 'payments#new'

  get       '/admin/dashboard',   to: 'admin#index'
  namespace :admin do
    resources :users, only: [:index, :change_role]
    post      '/users/:user_id/role',to: 'users#change_role'

    get       '/orders',            to: 'orders#index'
    post      '/orders/:order_id',  to: 'orders#confirm'
    delete    '/orders/:order_id',  to: 'orders#cancel'

    resources :categories, only: [:index, :create]
    put       '/categories/:category_id',     to: 'categories#update'
    delete    '/categories/:category_id',     to: 'categories#delete'

    resources :goods, only: [:index, :create]
    put       '/goods/:good_id',     to: 'goods#update'
    delete    '/goods/:good_id',     to: 'goods#delete'
    get       '/search/goods',       to: 'goods#search'

    resources :credits, only: [:create]

    resources :orders, only: [:index]
    post      '/orders/:order_id/credit',     to: 'credits#create'
    delete    '/orders/:order_id',            to: 'orders#cancel'


  end

end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :category
  has_and_belongs_to_many :shopping_carts
  has_and_belongs_to_many :orders

  before_destroy {shopping_carts.clear}
  before_destroy {orders.clear}

  has_attached_file :photo, :as => :owner

  def photo_from_url(url)
    self.photo = open(url)
  end

  validates :name, presence: true, length: { maximum: 100 }
  validates :price, presence: true, :numericality => {:greater_than => 0}
  validates :description, presence: true, length:  {minimum: 10 }
  validates :number, presence: true
  validates :number_of_reserved, presence: true
  validates :category_id, presence: true
  validates_attachment :photo,
                       presence: true,
                       size: { in: 0..512.kilobytes },
                       content_type: { content_type: ['image/jpg', 'image/jpeg', 'image/png'] }

  def self.search(text = '')
    sanitized = sanitize_sql_array(["to_tsquery('english', ?)", text.gsub(/\s/,"+")])
    Good.where("search_vector @@ #{sanitized}")
  end
end

app/controllers/admin/goods_controller.rb
class Admin::GoodsController < AdminController

  def index
    if !params[:text].nil?
      @goods = Good.search(params[:text]).paginate(page: params[:page], per_page: 30)
    elsif !params[:good].nil? && !params[:good][:category_id].nil?
      @goods = Good.where(category_id: params[:good][:category_id]).paginate(page: params[:page], per_page: 30)
    else
      @goods = Good.all.paginate(page: params[:page], per_page: 30)
    end

    @good = Good.new
    @categories = Category.all
  end

  def create
    @good = Good.new(good_params)
    @good.number_of_reserved = 0
    if @good.save
      redirect_to admin_goods_path
    else
      flash[:error] = 'Error adding good!'
      redirect_to admin_goods_path
    end
  end

  def update
    @good = Good.find(params[:good_id])
    @good.update_attributes(good_params)

    redirect_to admin_goods_path
  end

  def delete
    Good.delete(params[:good_id])

    redirect_to admin_goods_path
  end

  private
    def good_params
      params.require(:good).permit(:name, :price, :photo, :description, :category_id, :number)
    end

end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  load_and_authorize_resource

  def index
    if params[:order].nil?
      @goods = Category.find(params[:category_id]).goods.paginate(page: params[:page], per_page: 20)
    else
      order = params[:order] == 'desc' ? 'DESC' : 'ASC'
      @goods = Category.find(params[:category_id]).goods.order("price #{order}").paginate(page: params[:page], per_page: 20)
    end
  end


  def show
    @good = Good.find(params[:id])
  end

  def add_to_shopping_cart
    @current_user.shopping_cart << Good.find(params[:id])
  end

  def search
    @goods = Good.search(params[:text]).paginate(page: params[:page], per_page: 20)
  end

  private
    def good_params
      params.require(:good).permit(:name, :price, :number, :photo)
    end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/edit.html.erb
<h1>Goods#edit</h1>
<p>Find me in app/views/goods/edit.html.erb</p>

<%= form_for @good, url: goods_path, html: { multipart: true} do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :price %>
    <%= f.text_field :price %>

    <%= f.label :number %>
    <%= f.text_field :number %>

    <%= f.file_field :photo %>

    <%= f.submit 'submit changes' %>

<% end %>

app/views/goods/index.html.erb
<div class="container">
  <div id="products">
    <div class="list-group">
      <%= will_paginate %>
      <div class="panel panel-default">
        <div class="panel-body">
          <div>
            Sort by price:
            <div class="btn-group" role="group" aria-label="...">
              <%= link_to 'low to high',
                          { controller: 'goods', order: 'asc' },
                          class: 'btn btn-default' %>
              <%= link_to 'high to low',
                          { controller: 'goods', order: 'desc' },
                          class: 'btn btn-default' %>
            </div>
          </div>
        </div>
      </div>
      <% @goods.each do |good| %>
        <div class="list-group-item good-item">
          <div class = "row">
            <div class="col-md-4" >
              <figure class="pull-left">
                <%= image_tag good.photo,
                        class: 'good-photo',
                        alt: 'good' %>
              </figure>
            </div>
            <div class="col-md-5 good-description">
              <h2 class="list-group-item-heading">
                <%= good.name %>
              </h2>
              <p class="list-group-item-text">
                <%= good.description %>
              </p>
            </div>
            <div class="col-md-3 text-center">
              <h2> <%= good.price %> <small> UAH </small></h2>
              <%= link_to 'View', good_path(good.id),
                          class: 'btn btn-primary btn-lg btn-block btn-squared' %>
              <% if can? :manage, ShoppingCart %>
                <% if good.number > 0 %>
                  <%= link_to 'Add to cart', "/shopping_cart/goods/#{good.id}",
                          method: :post,
                          class: 'btn btn-success btn-lg btn-block btn-squared'
                  %>
                <% else %>
                  <a class="btn btn-success" disabled="true">Add to cart</a>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      <%= will_paginate %>
    </div>
  </div>
</div>

app/views/goods/new.html.erb
<div id="goods_catalog">
    <h2>Goods catalog<span class="label label-default"></span></h2>
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <h3 class = "text-center">Phones</h3>
                <img class = "catalog_img" src="images/categories/phones.png">
                <div class="caption">
                    <div class = "text-center">
                        <a href="cat-Phones.html" class="btn btn-primary" role="button">View</a>
                        <a href="cat-Phones.html" class="btn btn-success" role="button">Update</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <h3 class = "text-center">ADD NEW</h3>
                <img class = "catalog_img" class src="images/categories/new.png">
                <div class="caption">
                    <div class = "text-center">
                        <a href="new_category.html" class="btn btn-success" role="button">ADD</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/goods/new_good.html.erb
<div id="goods_catalog">
    <h2>All goods<span class="label label-default"></span></h2>
    <div class="panel panel-default">
        <div class="panel-body">
            <h4>5 items shown.</h4>
            <div>
                Sort by price 
                <div class="btn-group" role="group" aria-label="...">
                    <button type="button" class="btn btn-default">low to high</button>
                    <button type="button" class="btn btn-default">high to low</button>
                </div>
            </div>
        </div>
    </div>
    <div class="list-group-item" >
        <h4 class = "text-center">Add new good</h4>
        <form method="GET" id="register_forms">
            <div class="row">
                <div class="col-md-8">
                    <input type="name" class="form-control" placeholder="Good name" aria-describedby="basic-addon1">
                </div>
                <div class="col-md-3">
                    <input type="number" class="form-control" placeholder="Price" aria-describedby="basic-addon1">
                </div>
                <div class="col-md-1">
                    <h4>UAH</h4>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-4">
                    <h4>Upload good title picture</h4>
                    <form action="" method="post" enctype="multipart/form-data" id="js-upload-form">
                        <div class="form-inline">
                            <div class="form-group">
                                <input type="file" name="files[]" id="js-upload-files" multiple="">
                            </div>
                        </div>
                    </form>
                    <!-- Drop Zone -->
                    <div class="upload-drop-zone" id="drop-zone"></div>
                </div>

                <div class="col-md-8">
                    <textarea class="form-control" ceholder="Good description" rows="4" placeholder="Description"></textarea>
                </div>
            </div>
            <br>
            <div class="caption">
                <div class = "text-center">
                    <button type="submit" class="btn btn-success btn-lg" >Add good</button>
                </div>
            </div>
        </form>
    </div>

    <div class="list-group-item" >
        <form method="GET" id="register_forms">
            <div class="row">
                <div class="col-md-8">
                    <input type="name" class="form-control" placeholder="Good name" value = "Apple iPhone 7 128GB Gold" aria-describedby="basic-addon1">
                </div>
                <div class="col-md-3">
                    <input type="name" class="form-control" placeholder="Price" value="25 760" aria-describedby="basic-addon1">
                </div>
                <div class="col-md-1">
                    <span><h4>UAH</h4></span>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-4">
                    <figure class="pull-left">
                        <img class="media-object img-rounded img-responsive" src="images/apple_iphone_7_128gb_gold.png" alt="Apple iPhone 7 128GB Gold">
                    </figure>
                </div>

                <div class="col-md-8">
                    <textarea class="form-control" ceholder="Good description" rows="4" placeholder="Description">Экран (4.7", IPS, 1334x750)/ Apple A10 Fusion/ основная камера: 12 Мп, фронтальная камера: 7 Мп/ RAM 2 ГБ/ 128 ГБ встроенной памяти/ 3G/ LTE/ GPS/ Nano-SIM/ iOS 10
                    </textarea>
                    <p>Upload good title picture</p>
                    <form action="" method="post" enctype="multipart/form-data" id="js-upload-form">
                        <div class="form-inline">
                            <div class="form-group">
                                <input type="file" name="files[]" id="js-upload-files" multiple="">
                            </div>
                        </div>
                    </form>
                    <!-- Drop Zone -->
                    <div class="upload-drop-zone" id="drop-zone">
                    </div>
                </div>
            </div>
            <div class="caption">
                <div class = "text-center">
                    <button type="submit" class="btn btn-success btn-lg" >Update</button>
                    <button type="del" class="btn btn-danger btn-lg" >Delete</button>
                </div>
            </div>
        </form>
    </div>
</div>

app/views/goods/search.html.erb
<div class="container">
  <div id="products">
    <div class="list-group">
      <%= will_paginate %>
      <% @goods.each do |good| %>
          <div class="list-group-item">
            <div class = "row">
              <div class="media col-md-3" >
                <figure class="pull-left">
                  <%= image_tag good.photo,
                                class: 'media-object img-responsive',
                                width: '200',
                                height: '200',
                                alt: 'good' %>
                </figure>
              </div>
              <div class="col-md-6">
                <h2 class="list-group-item-heading">
                  <%= good.name %>
                </h2>
                <p class="list-group-item-text">
                  <%= good.description %>
                </p>
              </div>
              <div class="col-md-3 text-center">
                <h2> <%= good.price %> <small> UAH </small></h2>
                <%= link_to 'View', good_path(good.id), class: 'btn btn-primary btn-lg btn-block' %>
                <!--<button type="button" class="btn btn-primary btn-lg btn-block">View</button>-->
                <% if can? :manage, ShoppingCart %>
                    <% if good.number > 0 %>
                        <%= link_to 'Add to cart', "/shopping_cart/goods/#{good.id}",
                                    method: :post,
                                    class: 'btn btn-success btn-lg btn-block'
                        %>
                    <% else %>
                        <a class="btn btn-success" disabled="true">Add to cart</a>
                    <% end %>
                <% end %>
              </div>
            </div>
          </div>
      <% end %>
      <%= will_paginate %>
    </div>
  </div>
</div>

app/views/goods/show.html.erb
<div class="content">
  <div class="good-block">
    <div class="thumbnail">
      <%= image_tag @good.photo,
                    class: 'img-responsive',
                    alt: 'good' %>
      <div class="caption-full">
        <div class="page-header">
          <h2><%= @good.name %><span class="pull-right price"><%= @good.price %> UAH</span></h2>
        </div>
        <p><%= @good.description %></p>
      </div>
      <div class="text-right">
        <div class="btn-group btn-group-lg" role="group" aria-label="...">
          <div class="btn-group" role="group">
            <% if can? :manage, ShoppingCart %>
                <% if @good.number > 0 %>
                    <%= link_to 'Add to cart', "/shopping_cart/goods/#{ @good.id }",
                                method: :post,
                                class: 'btn btn-success btn-lg btn-block'
                    %>
                <% else %>
                    <a class="btn btn-success" disabled="true">Add to cart</a>
                <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>